#!/usr/bin/env python3
"""Generate publications.html from the LaTeX publication list.

Usage:
    python3 tools/build_publications.py [path/to/quanyan_zhu_publications.tex]

Re-run whenever the LaTeX publication list changes, then commit and push.
"""
import html
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TEX = ROOT.parent / "MyCV 2026 Summer" / "quanyan_zhu_publications.tex"
SKIP_SECTIONS = {"Citation Summary"}

ITEM_RE = re.compile(r"^\\item\[\\textbf\{\[([A-Z]+\d+)\]\}\]\s*(.*)$")
SECTION_RE = re.compile(r"^\\cvsection\{(.+?)\}")

DOI_RE = re.compile(r"DOI:\s*(10\.\d{4,9}/[^\s<]+?)(?=[\s.,;]*$|[\s,;])")
URL_RE = re.compile(r"\\url\{([^}]*)\}")
BARE_LINK_RE = re.compile(r"(?<![/\w])((?:link\.springer\.com|amazon\.com|www\.wiley\.com)/[^\s<]+?)(?=[.,;]?(?:\s|$))")
ARXIV_RE = re.compile(r"arXiv(?: preprint)?:?\s*(?:arXiv:)?(\d{4}\.\d{4,5})")


def latex_to_text(s: str) -> str:
    s = s.replace("\\&", "&").replace("\\%", "%").replace("\\_", "_")
    s = s.replace("\\dag{}", "†").replace("\\dag", "†")
    s = s.replace('{\\"o}', "ö").replace('{\\"u}', "ü").replace('{\\"a}', "ä")
    s = s.replace("---", "—").replace("--", "–")
    s = s.replace("\\textregistered{}", "®")
    return s


def to_html(raw: str) -> str:
    s = latex_to_text(raw)
    urls = []

    def stash(url: str, label: str) -> str:
        urls.append((url, label))
        return f"\x00{len(urls) - 1}\x00"

    s = URL_RE.sub(lambda m: stash(m.group(1) if m.group(1).startswith("http") else "https://" + m.group(1), "link"), s)
    s = DOI_RE.sub(lambda m: stash("https://doi.org/" + m.group(1).rstrip("."), "DOI"), s)
    s = BARE_LINK_RE.sub(lambda m: stash("https://" + m.group(1), "link"), s)

    s = html.escape(s, quote=False)
    s = re.sub(r"\$([A-Za-z])_([A-Za-z0-9])\$", r"\1<sub>\2</sub>", s)
    s = s.replace("$", "")
    # Emphasize the site owner's name in author lists.
    s = re.sub(r"\bQ\. Zhu\b", "<strong>Q. Zhu</strong>", s)
    s = ARXIV_RE.sub(lambda m: f'<a href="https://arxiv.org/abs/{m.group(1)}">arXiv:{m.group(1)}</a>', s)

    def restore(m):
        url, label = urls[int(m.group(1))]
        return f'<a href="{html.escape(url)}">{label}</a>'

    s = re.sub(r"\x00(\d+)\x00", restore, s)
    s = re.sub(r"(DOI|link):\s*(<a )", r"\2", s)
    s = re.sub(r"\s*DOI\s*(?=<a [^>]*>DOI)", " ", s)
    return s.strip()


def parse(tex: str):
    sections, current = [], None
    for line in tex.splitlines():
        line = line.strip()
        m = SECTION_RE.match(line)
        if m:
            name = m.group(1)
            current = None if name in SKIP_SECTIONS else {"name": name, "items": []}
            if current:
                sections.append(current)
            continue
        m = ITEM_RE.match(line)
        if m and current is not None:
            current["items"].append((m.group(1), to_html(m.group(2))))
    return sections


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def render(sections) -> str:
    total = sum(len(s["items"]) for s in sections)
    toc = "\n".join(
        f'      <a class="btn" href="#{slug(s["name"])}">{html.escape(s["name"])} ({len(s["items"])})</a>'
        for s in sections
    )
    blocks = []
    for s in sections:
        items = "\n".join(
            f'        <li><span class="k">[{k}]</span><span>{body}</span></li>' for k, body in s["items"]
        )
        blocks.append(
            f'    <section id="{slug(s["name"])}" data-section>\n'
            f'      <h2>{html.escape(s["name"])}</h2>\n'
            f'      <ol class="publist">\n{items}\n      </ol>\n    </section>'
        )
    return TEMPLATE.format(
        total=total, toc=toc, blocks="\n".join(blocks), updated=date.today().strftime("%B %Y")
    )


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Publications | Quanyan Zhu</title>
  <meta name="description" content="Complete publication list of Quanyan Zhu, New York University.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Source+Serif+4:opsz,wght@8..60,500;8..60,600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
  <!-- Generated by tools/build_publications.py. Edit the LaTeX source and re-run instead of editing this file. -->
  <nav class="nav"><div class="nav-inner">
    <a class="brand" href="index.html">Quanyan Zhu</a>
    <div class="nav-links">
      <a href="index.html#research">Research</a>
      <a href="index.html#books">Books</a>
      <a class="active" href="publications.html">Publications</a>
      <a href="index.html#group">Group</a>
      <a href="index.html#teaching">Teaching</a>
      <a href="index.html#contact">Contact</a>
    </div>
  </div></nav>

  <main class="wrap">
    <section>
      <h1>Publications</h1>
      <p>{total} entries, with my name in bold. See also
        <a href="https://scholar.google.com/citations?user=Qt2WDh0AAAAJ">Google Scholar</a>.</p>
      <div class="pub-toc">
{toc}
      </div>
      <div class="pub-tools">
        <input id="q" type="search" placeholder="Filter by title, author, venue, or year" aria-label="Filter publications">
        <span class="count" id="count"></span>
      </div>
    </section>
{blocks}
  </main>

  <footer class="wrap">Last updated {updated}.</footer>

  <script>
    const q = document.getElementById('q');
    const count = document.getElementById('count');
    const items = [...document.querySelectorAll('ol.publist li')];
    function filter() {{
      const terms = q.value.toLowerCase().split(/\\s+/).filter(Boolean);
      let shown = 0;
      for (const li of items) {{
        const text = li.textContent.toLowerCase();
        const ok = terms.every(t => text.includes(t));
        li.hidden = !ok;
        if (ok) shown++;
      }}
      document.querySelectorAll('[data-section]').forEach(sec => {{
        sec.hidden = !sec.querySelector('li:not([hidden])');
      }});
      count.textContent = terms.length ? shown + ' of ' + items.length + ' shown' : '';
    }}
    q.addEventListener('input', filter);
  </script>
</body>
</html>
"""


def main():
    tex_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TEX
    sections = parse(tex_path.read_text(encoding="utf-8"))
    out = ROOT / "publications.html"
    out.write_text(render(sections), encoding="utf-8")
    for s in sections:
        print(f"{s['name']}: {len(s['items'])}")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
